### ISSUE TITLE
Fresh install doesn't work

### ISSUE THREAD

**Issue by nikkolasg** [0xweb-org/0xweb#3]
I wanted to play with the CLI tool and fresh install on a fresh ubuntu machine doesn't work out.
```bash
$ npm i 0xweb -g
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@noble/hashes@1.3.3',
npm WARN EBADENGINE   required: { node: '>= 16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

added 97 packages, and audited 98 packages in 10s

7 packages are looking for funding
  run `npm fund` for details

9 vulnerabilities (4 moderate, 2 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

$ 0xweb
/usr/local/lib/node_modules/0xweb/lib/cli.js:5
    if (typeof module !== 'undefined' && Array.isArray(module?.paths)) {
                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/0xweb/index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

$ 0xweb init
/usr/local/lib/node_modules/0xweb/lib/cli.js:5
    if (typeof module !== 'undefined' && Array.isArray(module?.paths)) {
                                                              ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/0xweb/index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

What should I do ?

**Comment by nikkolasg** [comment]
Sorry, it was because of outdated node version on ubuntu APT repo. Updated node using this [post](https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version) and at least CLI tool can launch now.
